/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  transpilePackages: [
    '@udecode/plate',
    '@udecode/plate-ai',
    '@udecode/plate-basic-elements',
    '@udecode/plate-basic-marks',
    '@udecode/plate-block-quote',
    '@udecode/plate-break',
    '@udecode/plate-callout',
    '@udecode/plate-caption',
    '@udecode/plate-code-block',
    '@udecode/plate-combobox',
    '@udecode/plate-comments',
    '@udecode/plate-cursor',
    '@udecode/plate-date',
    '@udecode/plate-dnd',
    '@udecode/plate-docx',
    '@udecode/plate-emoji',
    '@udecode/plate-excalidraw',
    '@udecode/plate-floating',
    '@udecode/plate-font',
    '@udecode/plate-heading',
    '@udecode/plate-highlight',
    '@udecode/plate-horizontal-rule',
    '@udecode/plate-indent',
    '@udecode/plate-indent-list',
    '@udecode/plate-juice',
    '@udecode/plate-kbd',
    '@udecode/plate-layout',
    '@udecode/plate-line-height',
    '@udecode/plate-link',
    '@udecode/plate-markdown',
    '@udecode/plate-math',
    '@udecode/plate-media',
    '@udecode/plate-mention',
    '@udecode/plate-node-id',
    '@udecode/plate-reset-node',
    '@udecode/plate-resizable',
    '@udecode/plate-select',
    '@udecode/plate-selection',
    '@udecode/plate-slash-command',
    '@udecode/plate-suggestion',
    '@udecode/plate-tabbable',
    '@udecode/plate-table',
    '@udecode/plate-toggle',
    '@udecode/plate-trailing-block',
  ],
  experimental: {
    esmExternals: 'loose',
  },
};

module.exports = nextConfig;
//22